export function AppFooter() {
  return (
    <footer className="text-center p-2 bg-card/50 text-xs">
      Generated by{' '}
      <a href="https://github.com/solana-foundation/create-solana-dapp" target="_blank" rel="noopener noreferrer">
        create-solana-dapp
      </a>
    </footer>
  )
}
